version: "3.3"

services:
  app2:
    build: .
    image: app2
    restart: always
    ports:
      - 3001:80
    external_links: 
      - proxy
    networks:
      - app-network

networks:
  app-network:
    external: 
      name: app-network
