version: "3.3"

services:
  app2:
    build: .
    image: app2
    restart: always
    ports:
      - 3001:3001
    networks:
      - app-network

networks:
  app-network:
    external: 
      name: app-network
